### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by spdfalcon** [azizollahpayandeh/azizollahpayandeh#3]
مهندس سلام و عرض ادب این پروژتون باگ داره لطفا اصلاحش کنید

**Comment by spdfalcon** [comment]
همه جاش کلا پاک کن اصلا اخراجی

**Comment by azizollahpayandeh** [comment]
اقا دیگ تروقران اخراج نکنید!😥😥😭😭

**Comment by azizollahpayandeh** [comment]
هایاااااااااااااااا

**Comment by azizollahpayandeh** [comment]
fuck bitch
